#sample file to push on gitHub


#spring:
#  data:
#    mongodb:
#      uri: spring.data.mongodb.uri=mongodb+srv://bruceUser:StrongPass123!@cluster0.abcd.mongodb.net/businessproject?retryWrites=true&w=majority
#
#      database: mydb
#      auto-index-creation: true
#
#  main:
#    allow-circular-references: true
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: email@gmail.com
#    password: xxxx xxxx xxxx xxxx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable:true
#
#server:
#  port: 8081
#  servlet:
#    context-path: /journal
#
#weather:
#  api:
#    key: <key>
#
#weather_api_key: <key>